name: Auto-Label Issues

on:
  issues:
    types: [opened]

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Apply Labels Based on Content
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            ${{ contains(github.event.issue.title, 'Urgent') && 'Urgent' || '' }}
            ${{ contains(github.event.issue.body, 'Station 1') && 'Station 1' || '' }}
            ${{ contains(github.event.issue.body, 'Report Request') && 'report-request' || '' }}
