name: Auto Label Priority

on:
  issues:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Label based on priority
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            const body = issue.body.toLowerCase();
            const labels = [];

            // Check for priority in the issue body
            if (body.includes('priority')) {
              if (body.includes('urgent')) {
                labels.push('Urgent');
              } else if (body.includes('high')) {
                labels.push('High Priority');
              } else if (body.includes('normal')) {
                labels.push('Normal Priority');
              } else {
                labels.push('Low Priority');
              }
            } else {
              labels.push('Low Priority');
            }

            // Apply labels if any matched criteria
            if (labels.length > 0) {
              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: labels
              });
            }
