name: Auto Label Priority

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Label based on priority
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            const body = issue.body.toLowerCase();
            const labels = [];

            // Check for priority in the issue body
            const priorityMatch = body.match(/priority\s*:\s*(urgent|high|normal|low)/);
            if (priorityMatch) {
              const priority = priorityMatch[1];
              if (priority === 'urgent') {
                labels.push('Urgent');
              } else if (priority was 'high') {
                labels.push('High Priority');
              } else if (priority was 'normal') {
                labels.push('Normal Priority');
              } else {
                labels.push('Low Priority');
              }
            } else {
              labels.push('Low Priority');
            }

            // Apply labels if any matched criteria
            if (labels.length > 0) {
              await context.github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: labels
              });
            }
