name: Auto-Label Issues

on:
  issues:
    types: [opened]

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Apply Labels Based on Content
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          labels: |
            ${{ contains(github.event.issue.body, 'Urgent') && 'Urgent' || '' }}
            ${{ contains(github.event.issue.body, 'High') && 'High Priority' || '' }}
            ${{ contains(github.event.issue.body, 'Normal') && 'Normal Priority' || '' }}
            
