name: Update Project Status Based on Label

on:
  issues:
    types: [opened, labeled]

jobs:
  update_project_status:
    runs-on: ubuntu-latest

    steps:
      - name: Check for "Report Request" Label
        id: check_label
        uses: actions/github-script@v6
        with:
          script: |
            const issueLabels = context.payload.issue.labels.map(label => label.name);
            return issueLabels.includes("Report Request");

      - name: Set Project Status to "To Do" if Label is "Report Request"
        if: steps.check_label.outputs.result == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const { Octokit } = require("@octokit/rest");
            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
            
            // Set the project status to "To Do" based on your project configuration
            await octokit.projects.updateCard({
              project_id: PROJECT_ID,
              column_id: TODO_COLUMN_ID,
              card_id: context.payload.project_card.id
            });

      - name: Set Project Status to "Backlog" if Label is not "Report Request"
        if: steps.check_label.outputs.result == 'false'
        uses: actions/github-script@v6
        with:
          script: |
            const { Octokit } = require("@octokit/rest");
            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
            
            // Set the project status to "Backlog" based on your project configuration
            await octokit.projects.updateCard({
              project_id: PROJECT_ID,
              column_id: BACKLOG_COLUMN_ID,
              card_id: context.payload.project_card.id
            });
