name: Set Status Based on Report Type

on:
  issues:
    types: [opened]

jobs:
  set_status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Determine report type
        id: report_type
        run: |
          if [[ "${{ github.event.issue.title }}" == *"Bug or Data Error"* ]]; then
            echo "type=Bug" >> $GITHUB_ENV
          elif [[ "${{ github.event.issue.title }}" == *"Feature Request"* ]]; then
            echo "type=Feature" >> $GITHUB_ENV
          else
            echo "type=Other" >> $GITHUB_ENV

      - name: Set status based on report type
        run: |
          case "${{ env.type }}" in
            "Bug")
              echo "Setting status to 'Backlog'"
              ;;
            "Feature")
              echo "Setting status to 'Backlog'"
              ;;
            "Other")
              echo "Setting status to 'To Do'"
              ;;
          esac
