name: Set Status Based on Labels

on:
  issues:
    types: [opened]

jobs:
  set_status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Determine report label
        id: report_label
        run: |
          labels="${{ github.event.issue.labels }}"
          status="Backlog"
          for label in $labels; do
            if [[ "$label" == *"Report Request"* ]]; then
              status="To Do"
              break
            fi
          done
          echo "status=$status" >> $GITHUB_ENV

      - name: Set status based on report label
        run: |
          echo "Setting status to '${{ env.status }}'"
